### ISSUE TITLE
Unable to execute custom tasks under /etc/salt/tasks but /etc/salt/bla works

### ISSUE THREAD

**Issue by davama** [dmulyalin/salt-nornir#24]
Hello,

Playing around with custom tasks.

Copied over `job_data_echo.py` from [source](https://github.com/dmulyalin/salt-nornir/blob/master/test/salt_master_files/tasks/job_data_echo.py) into `/etc/salt/tasks`.

When attempt to execute i get this result:

```
> salt minion nr.task plugin="salt://tasks/job_data_echo.py" job_data='{"foo": 123}'  FB="bla-ap-*"
jid: 20221108162024053981
minion:
    Nornir-proxy MAIN PID 13 job failed: {'task_fun': 'salt://tasks/job_data_echo.py', 'kwargs': {'job_data': {'foo': 123}, 'FB': 'bla-ap-*', '__pub_fun': 'nr.task', '__pub_arg': [{'plugin': 'salt://tasks/job_data_echo.py', 'job_data': {'foo': 123}, 'FB': 'bla-ap-*'}], '__pub_tgt': 'minion', '__pub_jid': '20221108162024053981', '__pub_ret': '', '__pub_master_id': 'master-amer', '__pub_tgt_type': 'glob', '__pub_user': 'root'}, 'identity': {'jid': '20221108162024053981', 'uuid4': '49ac5e51-6b39-4a28-8668-dae9abb3e996', 'user': 'root', 'function': 'exec.nr.task'}, 'name': 'salt://tasks/job_data_echo.py'}, error:
    'Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/salt_nornir/proxy/nornir_proxy_module.py", line 1048, in _worker
        task_fun = _get_or_import_task_fun(job["task_fun"], loader=loader)
      File "/usr/local/lib/python3.9/site-packages/salt_nornir/proxy/nornir_proxy_module.py", line 719, in wrapper
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/salt_nornir/proxy/nornir_proxy_module.py", line 787, in _get_or_import_task_fun
        function_text = _file_download(plugin)
      File "/usr/local/lib/python3.9/site-packages/salt_nornir/proxy/nornir_proxy_module.py", line 765, in _file_download
        raise CommandExecutionError(
    salt.exceptions.CommandExecutionError: Salt-Nornir proxy pid 13, 'salt://tasks/job_data_echo.py' file download failed, saltenv 'base'
```

But if I place that same file under `/etc/salt/bla` it works fine:

```
> salt minion nr.task plugin="salt://bla/job_data_echo.py" job_data='{"foo": 123}'  FB="bla-ap-*"
jid: 20221108162151551395
minion:
    ----------
    bla-ap-1:
        ----------
        job_data_echo:
            ----------
            foo:
                123
```

Is there some configuration I may be missing?
Running: 
```
nornir-salt                  0.16.0
salt                         3004.2
salt-nornir                  0.16.0
```

Any input is much appreciated!

Thank you,
Dave

**Comment by davama** [comment]
Noticed `0.16.1` version but no change when upgraded.

Rebuild the docker image and now it works... \\( ﾟヮﾟ)/

Very odd... but nothing to do here
Closing
